package com.hellospringboot.hello;

import java.math.BigDecimal;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;

import com.hellospringboot.hello.config.CodeCampConfig;
import com.hellospringboot.hello.modellab.BankAccount;
import com.hellospringboot.hello.modellab.BankAccountRepository;

@SpringBootApplication
@EnableConfigurationProperties(CodeCampConfig.class)
public class HelloApplication {
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private BankAccountRepository bankRepository;
	
	@Autowired
	private CodeCampConfig config;

	public static void main(String[] args) {
		SpringApplication.run(HelloApplication.class, args);
	}

	@Bean
	public CommandLineRunner commandLineRunner(ApplicationContext ctx) {
		return args -> {

			System.out.println("Test Test");
			BankAccount account = new BankAccount("Oak", "Test", new BigDecimal(10000), 0);
			bankRepository.save(account);

			System.out.println("Test Configuration");
			System.out.println("Language = " + config.getLanguage());
			System.out.println("Student = " + config.getStudent());
//			Iterable<BankAccount> accs=bankRepository.findAll();
//			for(BankAccount acc:accs) {
//				System.out.println(acc);
//			}
//			account.setBalance(new BigDecimal(30000));
//			bankRepository.save(account);
//			BankAccount account2 = new BankAccount("Oakkkk", "Testtttt", new BigDecimal(10000), 1);
//			bankRepository.save(account2);
//			Iterable<BankAccount> accon=bankRepository.findAll();
//			for(BankAccount acc:accon) {
//				System.out.println(acc);
//			}
//			bankRepository.delete(account2);
//			System.out.println(bankRepository.findById("Oak").get());

		};

	}

}
